### ISSUE TITLE
Have you submitted to packagist.org?

### ISSUE THREAD

**Issue by cornernote** [tristanjahier/zoho-crm-php#1]
I see you have a composer.json, however the package doesn't exist here:

https://packagist.org/packages/tristanjahier/zoho-crm-php

Please consider submitting the package here:

https://packagist.org/packages/submit

**Comment by tristanjahier** [comment]
Hello @cornernote! You're right, I should publish this package on Packagist, and it is planned.
But I was waiting for my library to be stable and complete enough.

I am using this library in a private application and this is the way I am testing it. I still don't feel like this library is mature enough. Not every API method is supported yet and my code lacks documentation.

Anyway, thank you for your interest. 👍

**Comment by jsiebach** [comment]
I think it is always nice to include it on packagist anyway.  You can label this as a dev branch and let people know it's not production ready, but even so it will help people to include it in their programs and maybe even contribute with a pull request.  I'm using it to build a new app and would be willing to contribute if I find a way!

**Comment by tristanjahier** [comment]
Hello @jsiebach and thanks for your message.

Ok I'll consider publishing it on packagist sooner. But not in july because I have a huge workload at the moment. :/

Concerning the contributions, I don't think I'll accept pull requests until I reach a certain point when I will be sure about some things, for example naming conventions, coding style and the design of the library itself. As I already said, this is not stable enough and I'm not sure myself about some stuff.
I will write a CONTRIBUTING.md file when I'm ready.

However, I'll gladly accept issues to report bugs and improvement suggestions as for now! :+1:

**Comment by tristanjahier** [comment]
Hello again @cornernote and @jsiebach!

I just wanted to let you know that this library has now an official publication on Packagist.org! 🎉🍾

https://packagist.org/packages/tristanjahier/zoho-crm-php

It is tagged `0.1.0` and is still a **pre-release**.

You can now remove this GitHub repository from your `composer.json` and change the `require` instruction accordingly:

```
"require": {
    ...
    "tristanjahier/zoho-crm-php": "^0.1"
},
```

And yes it took (some) time. 😅
